#!/bin/bash

# 检查配置文件是否存在
if [ ! -e testcases/config.json ]; then
  echo "./testcases/config.json does not exist, please extract testcases to that directory."
  exit 1
fi

# 检查 jq 程序是否安装
if [ ! -e "$(which jq)" ]; then
  echo 'You need the program "jq" to use this script.'
  echo 'Run "sudo apt install jq" to install it.'
  exit 1
fi

# 检查测试用例文件是否存在
if [ ! -e "testcases/$1" -o -z "$1" ]; then
  if [ ! -z "$1" ]; then
    echo "Testcase $1 does not exist."
    exit 1
  fi
  echo "Usage: $0 <testcase name>"
  echo "Example: $0 basic_1"
  exit 1
fi

# 读取配置文件中的测试用例列表
list=$(jq ".$1[]" < "testcases/config.json")
if [ -z "$list" ]; then
  echo "invalid config"
  exit 1
fi

# 设置可执行文件路径
exename="build/bin/code"
if [ ! -e "$exename" ]; then
  echo "Please compile the ticket system and place the executable at \"$exename\""
  exit 1
fi

# 创建临时文件和目录的函数
function tmp () {
  if [ Darwin = "$(uname -s)" ]; then
    mktemp /tmp/ticket.XXXXXXXXXX
  else
    mktemp -p /tmp ticket.XXXXXXXXXX
  fi
}

function tmpdir () {
  if [ Darwin = "$(uname -s)" ]; then
    mktemp -d /tmp/ticket.XXXXXXXXXX
  else
    mktemp -d -p /tmp ticket.XXXXXXXXXX
  fi
}

# 创建临时目录并复制可执行文件
testdir="$(tmpdir)"
cp "$exename" "$testdir/"
exe="$testdir/$(basename $exename)"
cwd="$(pwd)"
basedir="$cwd/testcases/$1"

# 切换到临时目录
cd "$testdir"

# 遍历测试用例并运行可执行文件
for i in $list; do
  outfile="$(tmp)"
  echo "About to run input #$i..."
  time "$exe" < "$basedir/$i.in" > "$outfile"
  difffile="$(tmp)"
  if diff -ZB "$outfile" "$basedir/$i.out" > "$difffile"; then true; else
    cat "$difffile" | head -5
    backup="test-$1-$i-$(date '+%s').log"
    cp "$outfile" "$cwd/$backup"
    echo "Test failed on input #$i."
    echo "Output saved to $backup"
    exit 1
  fi
  rm "$outfile" "$difffile"
done

# 清理临时目录
rm -r "$testdir"
echo "Testcase complete, answer correct."
